# # Uncomment the next line to define a global platform for your project
# # platform :ios, '9.0'
#
# target 'SampleApp' do
#   # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!
#
#   # Pods for SampleApp
#
# end

platform :ios, '11.0'
use_frameworks!
source 'http://github.com/LivePersonInc/iOSPodSpecs.git' #LiveEngage Pod Repository

target 'SampleApp' do
  #LPMessagingSDK Includes: LPAMS.framework, LPInfra.framework, LPMessagingSDK.framework and  LPMessagingSDKModels.bundle
  pod 'LPMessagingSDK'
end
